### ISSUE TITLE
Add  ISO_3166 2 beside of addressCountry

### ISSUE THREAD

**Issue by mhf-ir** [google/schema-dts#105]
```
  "address": {
    "@type": "PostalAddress",
    "addressCountry": "IR",
    ...
```
```
  "address": {
    "@type": "PostalAddress",
    "addressCountry": "IR",
    "subdivisionISO": "IR-07",
    ...
```

https://en.wikipedia.org/wiki/ISO_3166-2

For example Tehran in IR (Iran) is **IR-07**
https://en.wikipedia.org/wiki/ISO_3166-2:IR#Current_codes

Key name suggest

* **subdivision**
* **subdivisionISO**
* **addressSubdivision**
* **addressSubdivisionISO**
* **addressCountrySubdivisionISO**
* **addressCountrySubdivision**
* **countrySubdivisionISO**
* **countrySubdivision**

**Comment by mhf-ir** [comment]
Seems this repo not hold for structure. :/

**Comment by Eyas** [comment]
Hi, this repo holds Typescript translations of schema.org, so if you go to schema.org/PostalAddress, this library generates .d.ts for it that looks the same.

Are you saying the core Schema.org has something we can't represent? Or did you intend to open a suggestion for Schema.org itself?

**Comment by mhf-ir** [comment]
@Eyas Thanks for quick response.

Yeah the subdivision of each country has ISO and i think schema.org could add this property for that.
It's not on Schema.org so i suggest it, of course in wrong repo i think.

**Comment by Eyas** [comment]
Yeah, got it. You'll want to open an issue here: https://github.com/schemaorg/schemaorg

Once you do, this repo would pick it up in the next release
