### ISSUE TITLE
NPM package sickly

### ISSUE THREAD

**Issue by mutech** [google/schema-dts#125]
NPM install failed because of missing "bin": "./dist/gen/cli/cli.js"

(version 0.7.1)

**Comment by Eyas** [comment]
oh no -- that's not right, let me look into this. Presumably this is happening when installing `schema-dts-gen`, right?

**Comment by mutech** [comment]
Yes. I build it from source, everything is good (build/test).

Fine code btw, the glitch was a good opportunity to get to see it. ;-)

**Comment by Eyas** [comment]
What's weird is that the file seems to packaged just fine: https://unpkg.com/browse/schema-dts-gen@0.7.1/dist/gen/cli.js

but npm install doesn't even work.

**Comment by mutech** [comment]
Weired in deed. Don't have the time to look into it, but I would guess that the archive is somehow damaged. It definitely doesn't extract cli.js or something is deleting it? Heisenbergs bones are twitching... :)

**Comment by Eyas** [comment]
Oh, haha. Looks like I missed a change to our output dir structure,

package.json says "dist/gen/**cli/**cli.js" exists, and I kept seeing "dist/gen/cli.js".

**Comment by Eyas** [comment]
Fixed in 0.7.3 :)

**Comment by mutech** [comment]
Thanks ;-)
