### ISSUE TITLE
Feature Request: schema-dts-gen --file=my-custom-schema-file.nt

### ISSUE THREAD

**Issue by eamon-otuathail** [google/schema-dts#145]
Currently schema-dts-gen accepts a HTTPS parameter for the schema:
  schema-dts-gen --ontology=https://schema.org/version/latest/schemaorg-all-https.nt

As an alternative, specifically for folks building external extensions who may wish to vary the contents of the ontology during automated builds (on devops machines, perhaps without network access), it would be useful if schema-dts-gen could instead accept the schema as a local file:
  schema-dts-gen --file=my-custom-schema-file.nt

**Comment by shnydercom** [comment]
please have a look at that draft and let me know comments/wishes :)

**Comment by eamon-otuathail** [comment]
That looks perfect - thanks!
