### ISSUE TITLE
BUG: schema-dts-gen and custom context - prefixes other than "schema" are ignored during generation of code for types

### ISSUE THREAD

**Issue by eamon-otuathail** [google/schema-dts#146]
schema-dts-gen accepts a `--context` parameter, which sets the value of the `@context` property. 

Imagine we have a custom schema for an external extension which we will call custom-schema.nt, which is a mix of all the schema.org types along with custom types, which we prefix with the demo namespace. We can auto-generate TypeScript code as follows: 
```
npx schema-dts-gen --ontology=https://somelocation.com/custom-schema.nt 
--context=schema:https://schema.org/,demo:https://example.com/demo/ > my-generated-code.ts
```
This nicely creates `WithContext` and `Graph`:
```typescript
export type WithContext<T extends Thing> = Graph | (T & {
    "@context": {
        "schema": "https://schema.org/";
        "demo": "https://example.com/demo/";
    };
});
export interface Graph {
    "@context": {
        "schema": "https://schema.org/";
        "demo": "https://example.com/demo/";
    };
    "@graph": readonly Thing[];
}
```
However, the custom `demo` prefix is ignored during code generation - currently we get:  
```typescript
interface DemoBase extends ThingBase {
    /** Indicates whether this resource is a template. */
    "https://example.com/demo/isTemplate"?: SchemaValue<Boolean>;
}
interface DemoLeaf extends DemoBase {
    "@type": "https://example.com/demo/Demo";
}
/** A Demo */
export type Demo = DemoLeaf;
```
whereas what would be nice would be: 
```typescript
interface DemoBase extends ThingBase {
    /** Indicates whether this resource is a template. */
    "demo:isTemplate"?: SchemaValue<Boolean>;
}
interface DemoLeaf extends DemoBase {
    "@type": "demo:Demo";
}
/** A Demo */
export type Demo = DemoLeaf;
```

**Comment by Eyas** [comment]
Thanks! I agree schema-dts-gen should take advantage of the `demo:` prefix here.

**Comment by Eyas** [comment]
I'm looking at my test cases and this is _supposed_ to work already. Can you provide a repro?

**Comment by Eyas** [comment]
Ah -- FWIW, if you change your `--context` to:

```
--context=schema:https://schema.org/,demo:https://example.com/demo
```

(i.e. without the final "/" for demo)

then it works as expected.

I'll make sure to include a fix for this in the near future.

**Comment by eamon-otuathail** [comment]
Hi Eyas, 

Yes, I tried this and it works very nicely, thanks - Eamon

>> FWIW, if you change your --context to:
>> --context=schema:https://schema.org/,demo:https://example.com/demo
>> (i.e. without the final "/" for demo) then it works as expected.
