### ISSUE TITLE
Error TS4023 when importing types

### ISSUE THREAD

**Issue by webdif** [google/schema-dts#168]
I have this piece of code:

```js
import { SportsEvent, WithContext } from 'schema-dts';

const getStructuredData = (): WithContext<SportsEvent> => ({
  '@context': 'https://schema.org',
  '@type': 'SportsEvent',
  // ...
});
```

I have the error TS4023 on this:
> Exported variable 'getStructuredData' has or is using name 'SportsEventLeaf' from external module 'myproject/node_modules/schema-dts/dist/schema' but cannot be named

How can I resolve this?

If I modify the `schema.d.ts` in my node_modules, and I export the SportsEventLeaf interface, it seems to solve this problem. But of course, it's not a real fix…

**Comment by Eyas** [comment]
Hmm, what TypeScript version are you using? 'Cannot be named' error were much more common in older versions of TS but I thought the checking here was relaxed.

**Comment by webdif** [comment]
I use TypeScript@3, do you think upgrading TypeScript does the trick?

**Comment by Eyas** [comment]
It's fixed starting TypeScript 3.9. You can upgrade to 3.9.7 or later.

BTW, if you _don't_ want to upgrade, the fix is to give an explicit type to your function:

```diff
 import { SportsEvent, WithContext } from 'schema-dts';
 
-export const getStructuredData = (): WithContext<SportsEvent> => ({
+export const getStructuredData: ()=>WithContext<SportsEvent> = (): WithContext<SportsEvent> => ({
   '@context': 'https://schema.org',
   '@type': 'SportsEvent',
   // ...
 });
```

**Comment by webdif** [comment]
Thank you so much 🙂

**Comment by chrisvltn** [comment]
This started to happen again.

```ts
import {BreadcrumbList} from 'schema-dts';

const data: BreadcrumbList = {'@type': 'BreadcrumbList'};
export const exportedFunction = () => ({data});
```

Will show the error:
```
Exported variable 'exportedFunction' has or is using name 'BreadcrumbListLeaf' from external module "..." but cannot be named. ts(4023)
```

If the function isn't exported, the error seems to not appear, though.
