### ISSUE TITLE
WithContext: Type '"https://schema.org"' is not assignable to type '"https://schema.org"'

### ISSUE THREAD

**Issue by DanielHara** [google/schema-dts#184]
I'm wondering how has anyone been able to use `WithContext`:

```
schema-dts@1.1.0
typescript@4.7.2
```

<img width="1021" alt="Screenshot 2022-05-27 at 11 28 24" src="https://user-images.githubusercontent.com/17606011/170693201-d90b5c71-40ec-47e9-ae03-456197bfc676.png">

**Comment by Eyas** [comment]
The schema is probably unnecessarily strict, but removing the final "/" should give you the right context.
