### ISSUE TITLE
URL type definition

### ISSUE THREAD

**Issue by fumiki** [google/schema-dts#24]
Can't asign string to type 'URL'.
<img width="252" alt=" 2019-05-30 10 43 28" src="https://user-images.githubusercontent.com/2100809/58602787-1c849880-82c9-11e9-85e8-ec953830d609.png">

### Error Message
> Type 'string' is not assignable to type 'URL | URL[] | undefined'.ts(2322)

I think it should be, but URL is defined as 

`{ "@type": "URL" } & string `

<img width="185" alt=" 2019-05-30 10 48 11" src="https://user-images.githubusercontent.com/2100809/58602641-a41dd780-82c8-11e9-9f2e-805b9814c821.png">

I'm not so familiar with schema.org and don't know about { "@type": "URL" }, but 

` { "@type": "URL" } | string `
is probably right?

**Comment by Eyas** [comment]
Thanks. Yes, I'd expect URL to be assignable to a string. Let me look into it.

**Comment by Eyas** [comment]
URL extends Text, so we should have done the right thing here. Looks like our .d.ts generator needs a fix here.

**Comment by Eyas** [comment]
Fixed in 0.4.1
