### ISSUE TITLE
Document WithContext

### ISSUE THREAD

**Issue by antoinerousseau** [google/schema-dts#30]
I didn't understand why I couldn't add `"@context": "https://schema.org"` to my TypeScript object of type `Product`, until I realized it had to be of type `WithContext<Product>`. Seems necessary for Google Structured Data, so I think it should be in the README? If you agree, I can make the PR.

**Comment by Eyas** [comment]
Sounds like a good thing to document. Happy to review a PR here!

The basic thing is we only want WithContext<X> on the top-level item (your nested objects shouldn't have a different context than their parents).

The React-specific package (react-schemaorg) forces WithContext<T>, but it seems wrong that we don't make a mention of it here at all.

**Comment by antoinerousseau** [comment]
@Eyas done @ #31 \o/
