### ISSUE TITLE
Is It Possible to Have a Sitelinks Searchbox?

### ISSUE THREAD

**Issue by adonig** [google/schema-dts#33]
The compiler does not like the "query-input" property on a SearchAction.

<img width="682" alt="Screen Shot 2019-09-13 at 13 38 00" src="https://user-images.githubusercontent.com/900404/64859921-dfe86d00-d62b-11e9-8d78-a35aaa79a9da.png">

If I check the source code of schema-dts, I only see a property query. It seems like schema.org has something called a property constraint: https://schema.org/docs/actions.html#part-4

Am I doing something wrong here? Is there a way to make this work?

**Comment by Eyas** [comment]
Interesting. Thanks for pointing this out.

As of now there's no native support for these extensions (I'll need to think about how to do that thoughtfully). One thing you can do is to extend SearchAction with your own type:

```ts
type MySearchAction = SearchAction & {
  "query-input": PropertyValueSpecification | String;
};
```

or similar.

TypeScript's excess property checking will still complain with the current code, but assigning to `MySearchAction` at an intermediary would also address this.

This might be deserving of a better answer, but right now schema-dts is very much intended as a types-only annotation of schema.org schema. Unfortunately schema.org is not really a strict schema as much as a set of conventions. In this case, the Actions schema is especially open for adding properties based on intent.

I'd like to support this. But it isn't immediately obvious how, so I'm open to ideas!

**Comment by adonig** [comment]
Extending SearchAction works sufficiently. Thank you 🙏

**Comment by mayank2108** [comment]
> Extending SearchAction works sufficiently. Thank you 🙏

Can you write the full code that solved your issue?

**Comment by adonig** [comment]
@mayank2108 I apologize for having overlooked your reply. While it is nearly half a year late, I hope this still helps:

```
  type SearchActionWithQueryInput = SearchAction & {
    "query-input": string
  }

  const searchAction: SearchActionWithQueryInput = {
    "@type": "SearchAction",
    target: `https://www.example.org/search?q={search_term_string}`,
    "query-input": "required name=search_term_string",
  }

  const websiteSchema: WithContext<WebSite> = {
    "@context": "https://schema.org",
    "@type": "WebSite",
    url: `https://www.example.org`,
    potentialAction: searchAction,
  }
```
