### ISSUE TITLE
Invalid link in announcement post

### ISSUE THREAD

**Issue by Vinnl** [google/schema-dts#49]
Didn't find a better place to report, so... On https://opensource.googleblog.com/2019/11/improving-developer-experience-for.html, the first mention of "schema-dts" links to https://opensource.google/projects/schema-dts

Unfortunately, that page just says "No results found."

![image](https://user-images.githubusercontent.com/4251/68993477-de7c3080-0878-11ea-955a-46647bd5b10f.png)

**Comment by Eyas** [comment]
Can you try again? Looks like it's working for me.

**Comment by Vinnl** [comment]
Still not working, unfortunately.
