### ISSUE TITLE
[question] JSON marshal/unmarshal?

### ISSUE THREAD

**Issue by knoguchi** [google/schema-dts#95]
Thanks for showing me how to define the types of JSON-LD in TypeScript.   I like the compiler and IDE gives me warnings when I try to set bad fields and values.   To serialize to JSON is also super easy.

Now, my question is how to unmarshal JSON to the typed objects?  I thought I could get the @type and assert the type but so far not successful.  If you already have a solution please let me know.

**Comment by knoguchi** [comment]
This is what I'm thinking.  But I don't like `let typed` has no type.

```
export declare type Number = number;
export declare type Text = string;

type Base = {
  '@type': Text;
  common: Text;
}

type TypeA = {
  a_only?: Text;
} & Base;

type TypeB = {
  b_only?: Text;
} & Base;

let data : TypeA = {
  "@type": "TypeA",
  common: 'common message',
  a_only: 'this is a'
}

let typed
if (data["@type"] == "TypeA") {
  typed = <TypeA> data;
  console.log(typed.a_only); // no error
} else if (data["@type"] == "TypeB") {
  typed = <TypeB> data;
  console.log(typed.b_only); // no error
} else {
  typed = <Base> data;
}
console.log(typed.common);
console.log(typed.a_only); // error
console.log(typed.b_only); // error
```

**Comment by Eyas** [comment]
To get a `["@type"] === "foo"` check work you'd need the object behind tested to be a closed discriminated union of possibilities matching this type.

If a variable`data` is any or unknown (e.g. as a result of JSON.parse), then it's @type property being "foo" or "bar" won't narrow things at all.

On the other hand if `data` was `TypeA | TypeB` then testing the `@type ` property will narrow it down to A/B.

If data was a union, then you won't even need typed. And you wouldn't need to reassign or cast.

Hope that helps

**Comment by knoguchi** [comment]
You answered all of my questions despite my vague post.  `TypeA | TypeB` worked well.   Thanks for the answer.

**Comment by Eyas** [comment]
No problem! Glad it helped
